name: project2
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        env:
          TOKEN: ${{ secrets.TOKEN }}
